# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Stock Check

on:
#  schedule:
#    - cron: '* * * * *'
  issues:
    types:
      - opened

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Caching and Check
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cache/ms-playwright/
          ./venv/
        key: ${{ runner.os }}-browsers-venv
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv
        python -m venv venv
        source ./venv/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        playwright install
    - name: Run Bot
      env: 
        SESSION_ID: ${{ secrets.SESSION_ID }}
        URL: ${{ secrets.URL }}
        WEBUSERNAME: ${{ secrets.WEBUSERNAME }}
        WEBPASSWORD: ${{ secrets.WEBPASSWORD }}
      run: |
        if [ -f $VIRTUAL_ENV ]; then source ./venv/bin/activate; fi 
        python main.py
